patient_metadata: data/otu_large.csv
core: data/core.tsv
pan: data/pan.tsv
gene_key: data/grouped_gene_key.tsv
tree: data/cytokine_rooted_tree.tree
ml_methods:
 - glmnet
 - rf
 - svmRadial
kfold: 5
ncores: 36
nseeds: 100
cytokine:
  - serum_IL.6
  - serum_TNFa
  - serum_Procalcitonin
